USE [master]
GO
IF NOT EXISTS
    (SELECT name FROM [master].[sys].[syslogins] WHERE name = '[USERNAME]')
BEGIN
    CREATE LOGIN [USERNAME] WITH PASSWORD=N'12345', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
END
GO

USE [Apply4Law3_Dev]
GO

IF NOT EXISTS
	(SELECT * FROM sys.database_principals WHERE name = '[USERNAME]')
BEGIN
	CREATE USER [USERNAME] FOR LOGIN [USERNAME]
	ALTER USER [USERNAME] WITH DEFAULT_SCHEMA=[USERNAME]
	EXEC('CREATE SCHEMA [USERNAME] AUTHORIZATION [USERNAME]')	
END
GO

USE [AllhiresDev]
GO

IF NOT EXISTS
	(SELECT * FROM sys.database_principals WHERE name = '[USERNAME]')
BEGIN
	CREATE USER [USERNAME] FOR LOGIN [USERNAME]
	ALTER USER [USERNAME] WITH DEFAULT_SCHEMA=[USERNAME]
	EXEC('CREATE SCHEMA [USERNAME] AUTHORIZATION [USERNAME]')
END
GO
