
USE [apply4law3]
GO

IF NOT EXISTS
    (SELECT * FROM sys.database_principals WHERE name = '[USERNAME]')
BEGIN
    CREATE USER [USERNAME] FOR LOGIN [GBP\ISUR_A4L_USERNAME] WITH DEFAULT_SCHEMA=[USERNAME] 
    EXEC('CREATE SCHEMA [USERNAME] AUTHORIZATION [USERNAME]') 
END
GO

USE [apply4law3testing16]
GO

IF NOT EXISTS
    (SELECT * FROM sys.database_principals WHERE name = '[USERNAME]')
BEGIN
    CREATE USER [USERNAME] FOR LOGIN [GBP\ISUR_A4L_USERNAME] WITH DEFAULT_SCHEMA=[USERNAME] 
    EXEC('CREATE SCHEMA [USERNAME] AUTHORIZATION [USERNAME]')
END
GO

USE [apply4law]
GO
IF NOT EXISTS
    (SELECT * FROM sys.database_principals WHERE name = '[USERNAME]')
BEGIN
    CREATE USER [USERNAME] FOR LOGIN [GBP\ISUR_A4L_USERNAME] WITH DEFAULT_SCHEMA=[a4lapplocker] 
    EXEC('CREATE SCHEMA [USERNAME] AUTHORIZATION [USERNAME]')
END
GO

USE [allhires]
GO
IF NOT EXISTS
    (SELECT * FROM sys.database_principals WHERE name = '[USERNAME]')
BEGIN
    CREATE USER [USERNAME] FOR LOGIN [GBP\ISUR_A4L_USERNAME] WITH DEFAULT_SCHEMA=[USERNAME]
    EXEC('CREATE SCHEMA [USERNAME] AUTHORIZATION [USERNAME]')
END
GO

USE [allhirestesting]
GO
IF NOT EXISTS
    (SELECT * FROM sys.database_principals WHERE name = '[USERNAME]')
BEGIN
    CREATE USER [USERNAME] FOR LOGIN [GBP\ISUR_A4L_USERNAME] WITH DEFAULT_SCHEMA=[USERNAME]
    EXEC('CREATE SCHEMA [USERNAME] AUTHORIZATION [USERNAME]')
END
GO